### ISSUE TITLE
DynamicMapLayer redraw function missing

### ISSUE THREAD

**Issue by UsgsMonkey** [SVoyt/esri-leaflet-dynamic-advanced#8]
This may be a gap in my JavaScripting knowledge but I'm also not sure of your implementation.  The original DynamicMapLayer has a 'redraw' function.  If this class is an extension of that class, is that root class still exposed somewhere where I can get a hook to call 'redraw' or do you need to explicitly expose this function through your new API?

(I searched the prototype chain for the DynamicMapLayerAdvanced object in my implementation and was unable to locate any 'redraw' function)

Pretty-please restore the 'redraw' function into this implementation (if this is the recommended resolution)!  While your class solves some key issues for us, if it lacks this functionality this just creates a whole new set of problems...

**Comment by jgravois** [comment]
the method you're looking for is [`_update()`](https://github.com/SVoyt/esri-leaflet-dynamic-advanced/blob/ff62386136d0108048255c37b60df2c61bd93db6/src/DynamicMapLayerAdvanced.js#L397-L419).

in esri-leaflet, [`DynamicMapLayer.redraw()`](https://github.com/Esri/esri-leaflet/blob/master/src/Layers/RasterLayer.js#L185-L187) just calls `_update()` internally.

**Comment by SVoyt** [comment]
DynamicMapLayerAdvanced extends L.Layer, not DynamicMapLayer. So, you should use `_update()` function as @jgravois said.

**Comment by UsgsMonkey** [comment]
I think I hear angels singing.  Thanks guys :)

**Comment by UsgsMonkey** [comment]
That did the trick.  Thanks again!
